moscajs/aedes

README.md

The example suggested that the authorizeSubscribe method receives the topic as a parameter (like in mosca) but it takes a subscription object.

Update authorizeSubscribe documentation in README

---

README.md

The README.md example code does not run as-is unless the `require('./aedes')` is changed to `require('aedes')` since the module is installed via `npm install aedes --save`.

Fix require() statement in README example

---

aedes.js
lib/handlers/subscribe.js
test/events.js
test/qos1.js

Do not forward or store QoS 1/2 on $SYS/# for # subs.

---

lib/client.js
test/regr-21.js

Fixed #21.
@cefn please test and see if it solves your issue.

Stop ingesting packets after the client has errored

---

lib/client.js
test/auth.js
test/qos1.js

When using TLS like this:
```
var tlsServer = tls.createServer(options, function(s){  
console.log('secure connection established');
aedes.handle(s);
});
tlsServer.listen(config.ports.tcptls);
```
Sometimes happens that client does not connect completely (e.g. using some ssl scan tool like https://github.com/rbsec/sslscan) and **end-of-stream** is firing a callback which is **client.close()**. In that situation, client is not connected to the broker. That causes incorrect decrement of connected clients in broker.unregisterClient()

prevent null client unregister

---

lib/handlers/pubrel.js
test/qos2.js

This attempts to resolve https://github.com/mcollina/aedes/issues/34 by adding the client to the `publish` method called in the PUBREL handler.

Add client to published callback for QoS 2

---

aedes.js
package.json
test/auth.js

`authenticate`, `authorizePublish`, `authorizeSubscribe`, and `published` methods can be passed in the configuration options when initializing the broker or can be set after the fact as it works now:
```javascript
var aedes = require('aedes')({
authenticate: function (client, username, password, callback) {
callback(null, username === 'skroob' && password === '12345')
}
)};
```
Also refactored the options ab it to use a `defaults` function for clarity.
This addresses https://github.com/mcollina/aedes/issues/9

Add options for overriding methods in broker creation

---

README.md
lib/handlers/puback.js
test/client-pub-sub.js

This addresses https://github.com/mcollina/aedes/issues/10 and emits a `delivered` event when a PUBACK is received.

Add 'delivered' event on PUBACK handler

---

README.md
aedes.js
lib/client.js
test/auth.js

Hello. I've added the method we talked about. However, I'm not very sure about the arguments of the callback. Right now, it only looks at err, the rest being modified on the original object.
I did see a slight drop in perfomance, about 2-5% after adding the method, without supplying anything custom in the config.

Added authorizeForward

---

lib/client.js
lib/handlers/connect.js
lib/handlers/subscribe.js
test/basic.js
test/qos1.js

Fixes #52 
@bblumberg please verify

Reduce the QoS to 0 when sending retained messages.

---

README.md
lib/handlers/connect.js
test/auth.js

This has the extra error codes Aedes doesn't return

Handling for other return codes

---

lib/handlers/connect.js
test/basic.js
test/meta.js

Emitted a connackSent event to allow implementing operations required after connack has been sent.

Emit connackSent event

---

README.md
aedes.js
test/client-pub-sub.js
test/qos2.js

An online/offline feature for aedes

presence module for aedes

---

README.md

Updated the docs to match the new parameter expectation.

Docs: instance.publish(packet) expects an aedes-packet object

---

lib/handlers/connect.js

It used to: disconnect after 1501 * keepalive time
It now: disconnects after 1500 * keepalive time + 1 millisecond
This solves issues with large keepalive numbers sent with the connect packet.

Fixed glitch in keepaliveInterval

---

aedes.js
test/will.js

Related to #96 
@mcollina @nguyenthenguyen Please verify

Broker Id should be updated when streamed

---

lib/handlers/connect.js
lib/handlers/subscribe.js
lib/handlers/unsubscribe.js
package.json

1. Fix `addSubscriptions` being called per topic, it should be called once for the topics array as said in README
2. Fix `addSubscriptions` being called when restoring client subs, it this case aedes-cached-`persistence#addedSubscriptions` should only be called.
3. Don't emit subscribe on restoring client subs.
fix number 1 and 2 are fast & dirty, but that not bad.
A better fix would need 
- changing the whole handleSubscribe, not to call `storeSubscriptions` per topic
- introducing a `restoreSubscriptions` method
- moving up (and renaming for a better one) `addedSubscriptions` up into aedes subscribe handler, I don't think [this](https://github.com/mcollina/aedes-cached-persistence/blob/master/index.js#L79-L93) is a implementation that should be inside aedes-cached-persistence
however …

Fix invalid subscription handling

---

lib/handlers/publish.js
lib/handlers/subscribe.js
lib/handlers/unsubscribe.js
lib/handlers/validations.js
test/basic.js

Fixes #132.
@ckrey is the correct behavior to severe the connection on a bad topic SUBSCRIBE?

Validate topics

---

aedes.js
lib/handlers/subscribe.js
test/events.js

Fixes: https://github.com/mcollina/aedes/issues/135
@ckrey

Do not forward $SYS topics for +/# subscriptions.

---

lib/handlers/subscribe.js
lib/handlers/unsubscribe.js
test/auth.js

Fixes https://github.com/mcollina/aedes/issues/133

Guarantee granted always come in the right order

---

lib/client.js
test/basic.js

Clear up drain listeners in the case of an error

---

aedes.js
package.json
test/basic.js
test/qos1.js

Fix for <a> https://github.com/mcollina/aedes/issues/110 </a>

Retain false when subscriber is active

---

lib/handlers/subscribe.js

If the current client is a clean session, a subscription should not be stored in persistence as it is not a persistent session.

clean clients should not have persistent subscription records.

---

lib/handlers/unsubscribe.js
test/basic.js
test/meta.js

@mcollina , i've implemented #145, please review if it's ok to merge.

Emit 'unsubsribe' event when client has clean=true on disconnect #145

---

.gitignore
package.json
test/typescript/tsconfig.json
test/typescript/typings.ts
tslint.json
types/index.d.ts

Finishing the Typescript typings spree, following https://github.com/mqttjs/mqtt-packet/pull/39.
Unfortunately `aedes` needs export assignment, which limits the usage of the typinngs somewhat, but it's still very helpful.

Adding Typescript typings.

---

lib/handlers/connect.js

emit client errors like unauthorized

---

lib/client.js
test/will.js

Fixed for crash at [comment](https://github.com/mcollina/aedes/pull/212/files#diff-50cfa59973c04321b5da0c6da0fdf4feL253)

delivers a will waits for authorization

---

lib/handlers/connect.js
test/will.js

Fixed issue #214. It turned out that LWT are being stored and sent on authentication failure as well. I fixed that and added 2 test cases - one for keep-alive timeout being triggered during authentication and one for authentication failure.

[Security] Fixed issue #214

---

README.md
aedes.js
test/basic.js

This allows `id` as an option when constructing a broker. When not defined, defaults to the old default of `shortid()`.

allow broker id in options

---

lib/handlers/subscribe.js
test/client-pub-sub.js

Hey @mcollina 
This PR includes a failing test case for the bug mentioned in #200

test case for retained message on negated subsciption bug

---

lib/client.js
test/qos2.js

Downgrade qos to client sub if needed

---

aedes.js
test/typescript/typings.ts
types/index.d.ts

With current type definitions it's not possible to use explicit typing. I changed them based on [this template](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/declaration%20files/templates/module-function.d.ts.md) to allow to import all defined types.
Besides that, I added an `AuthenticateError` type and changed typescript tests to use explicit typing in a few places. I also changed some names in tests file to avoid naming collisions and to be more in line with other tests.
Not being able to use explicit typing is a problem in my project, so I hope you will find these changes useful.

Improve Typescript typings to allow explicit typing

---

README.md
lib/handlers/subscribe.js
test/auth.js

1.fix bug while client(MQTT.js) subscribing to an Array of topics. I am curious the original line use only subscriptions[0] in if condition that would ignore the rest topics in an Array.
-2.fix bug while negating a subscription. The original logic is setting sub to null that will cause series problem. e.g: to negate multi topics and to persistent negated topics (which QoS is still 0 in storage).
-----------------
I retract #2 to pass test case with bugs I mentioned. Maybe you can change this part while you have time :)
--------------------------
I fixed negated topics persistence bug in the third commit.
Multi topics negating bug is still there.
```
instance.authorizeSubscribe = function (client, sub, callback) {
if (sub.topic === 'aaaa') {
sub = null
}
if (sub.topic === 'bbbb') { //bug …
```

Fix bug while client subscribing to an Array of topics.

---

test/keep-alive.js

Travis CI sometimes is too slow, and is causing aedes broker not respond and fails the 'disconnect if a connect does not arrive in time' test

Prolong waiting time

---

lib/handlers/index.js
test/basic.js

> After a Network Connection is established by a Client to a Server, the first Packet sent from the Client to the Server MUST be a CONNECT Packet [MQTT-3.1.0-1].
> A Client can only send the CONNECT Packet once over a Network Connection. The Server MUST process a second CONNECT Packet sent from a Client as a protocol violation and disconnect the Client [MQTT-3.1.0-2]

Check CONNECT and add tests

---

test/qos1.js

In a parallel testing, publish and suback may not arrive in order in different machines.

More reliable test in 'subscribe and publish QoS 1 in parallel'

---

lib/client.js
lib/handlers/connect.js
lib/handlers/publish.js
lib/write.js
test/basic.js
test/close_socket_by_other_party.js
test/meta.js
test/retain.js
test/will.js

This PR replaces PR https://github.com/mcollina/aedes/pull/282
and solves following issues
- https://github.com/mcollina/aedes/issues/237, Aedes not properly releasing connections
- https://github.com/mcollina/aedes/issues/246, Multiple clients subscribe same topic, no subscribers will receive message if one of them is closed by destroying socket

Gracefully close clients & properly release connections

---

package.json
test/qos1.js

The items in offline queue should be same as what we inserted.
However it is related to aedes-persistence. The PR https://github.com/mcollina/aedes-persistence/pull/31 will fix the CI test.

Added a unit test, check offline queue in QoS 1

---

aedes.js
test/meta.js

It should fix the issue https://github.com/mcollina/aedes/issues/286

Packet in published event should be identical with what client publishes

---

lib/client.js
lib/handlers/subscribe.js
test/retain.js

From MQTT 3.1.1 spec
> If the RETAIN flag is set to 1, in a PUBLISH Packet sent by a Client to a Server, the Server MUST store the Application Message and its QoS, so that it can be delivered to future subscribers whose subscriptions match its topic name [MQTT-3.3.1-5]
We store the retained message QoS in a persistence store. If the retain message is QoS 1
Subscriber (QoS 2) will get the retained msg in QoS 1
Subscriber (QoS 1) will get the retained msg in QoS 1
Subscriber (QoS 0) will get the retained msg in QoS 0 (downgraded)

The QoS of retained messages should depend on subscribers

---

test/auth.js
test/basic.js
test/client-pub-sub.js
test/events.js
test/keep-alive.js
test/not-blocking.js
test/qos1.js
test/qos2.js
test/regr-21.js
test/retain.js
test/will.js

For robustness, it is safer to state test plan number.

Enhance test & added test plan number

---

README.md
test/client-pub-sub.js

Fixed tests that will produce duplicate PUBLISH packets in directly push to a QoS 2 client. #281
and state packet type in Broker `ack` event #257

Enhance cilent pub sub tests

---

lib/client.js

Attempt to fix "Maximum call stack size exceeded"  …
Reported in #193
This could be reproduced using benchmark/server.js, benchmark/throughputCounter.js and benchmark/bombing.js
Once all three processes are up, stay a while and SIGINT the throughtputCounter.js

Fixed "Maximum call stack size exceeded"

---

lib/handlers/subscribe.js
test/auth.js
test/helper.js

If there are duplicated topics in subscriptions, no matter what QoS is, we pick the last one.
say the subscriptions in SUBSCRIBE are
```
[{ topic: 'hello', qos: 1 }, { topic: 'hello', qos: 0 }]
```
the actual subscription is only `{ topic: 'hello', qos: 0 }`
Vernemq and mosquitto are in same behaviour.

Dedupe subscriptions

---

lib/handlers/connect.js
lib/handlers/subscribe.js
test/retain.js

For issue https://github.com/mcollina/aedes/issues/300, and probably for issue https://github.com/mcollina/aedes/issues/126
Based on MQTT Spec section 3.1.2.4, we should not send retained messages when we restore subscriptions with clean=false clients.

Not send retained messages when restoring subscriptions for clean=false clients

---

README.md
aedes.js
lib/client.js
test/connect.js

Servers based on websocket-stream require access to the original HTTP request headers in order to access the `X-Forwarded-For` or any other interesting HTTP header. 
I've done the minimal possible work to attach the original HTTP request to aedes' Client object so that it's available later on.

Add websocket/http request to client object during connection

---

README.md
aedes.js
examples/proxy/index.js
examples/proxy/package.json
lib/client.js
lib/protocol-decoder.js
package.json
test/basic.js
test/connect.js
test/meta.js
test/will.js

Hey,
I'm using this project very often and i noticed that having a nice ipAddress property might be useful for me and other users ( to use in preConnect hook for example ).
Since it's important to have a correct information, i thought it would be interesting to add a trustProxy property to the broker. Then if aedes is placed behind load balancer / proxy,  we could use http headers (x-real-ip / x-forwarded-for ) in case of websocket connection or proxy protocol in case of tcp socket.
So i implemented proxy-protocol-js to test incoming client's buffer and to try retrieving source ip address.
I've been adding an example and some tests.
Please let me know if this feature is useful and not out of the scope of aedes.

Proxy and ip decoder

---

lib/handlers/connect.js
test/will.js

Delete existing will message on client connect

---

lib/client.js
lib/handlers/connect.js
lib/handlers/index.js
test/basic.js
test/will.js

- removed unused _handling var
- initialize authorized var to false and refactor it to a private var
- refactored parser var to a private var
- refactored disconnected var, it is a flag to control not to send Will when DISCONNECT, and not used to reflect the connection state.

[chore] Refactored variables

---

lib/handlers/index.js
test/close_socket_by_other_party.js
test/connect.js
test/helper.js

We have already followed [MQTT-3.1.0-2] spec to block 2nd CONNECT. This only applies to when `connected=true` clients. This PR is to stop any 2nd CONNECT even in the early preConnect stage where `connected=false`

[chore] Reject 2nd CONENCT while in preConnect

---

lib/handlers/connect.js
test/close_socket_by_other_party.js
test/connect.js
test/will.js

Once broker is closed while in authentication, we stop processing pending actions (e.g. set keepalive, restore subscriptions, register clients etc.) as quick as possible in resource wise.

[chore] Stop series of connect actions asap if broker is closed

---

test/connect.js

@mcollina Is it better to add .catch() block rather than try/catch?
any differences?

Added a proper catch block for handling errors

---

lib/handlers/connect.js
test/connect.js
test/will.js

We have already emitt errors in callback, it is not necessary to explicitly emit error by ourselves

Fixed duplicate emitting error event

---

test/auth.js
test/helper.js

The connected callback is to simulate the `connected` event, it should be called only when `returnCode === 0`

Fixed helper connected callback

---

package.json
test/auth.js
test/basic.js
test/client-pub-sub.js
test/close_socket_by_other_party.js
test/connect.js
test/events.js
test/helper.js
test/keep-alive.js
test/meta.js
test/not-blocking.js
test/qos1.js
test/qos2.js
test/regr-21.js
test/retain.js
test/topics.js
test/will.js

- replaced broker setTimeout autoClose with tearDown
- added missing t.plan
- dropped t.end
- fixed some tests to better adapt tap
- dropped nyc, tap has built-in coverage support

Switch tape to tap

---

lib/handlers/index.js
test/basic.js
test/meta.js
test/retain.js
test/will.js

end() will send final data and allow some i/o activity to finish before destroying socket.
MQTT-3.14.4-2 states "MUST NOT send any more Control Packets on that Network Connection". In some case aedes still deliverQoS data to subscribers via  mqemitter when subscriber is conn.end(), broker then raises "connection closed" error.
Once we destroy the socket, mqemitter will not trigger deliver data to closed subscriber.
Fixed issue https://github.com/moscajs/aedes/issues/396

Destroy socket when DISCONNECT sent

---

test/events.js

Only emit `closed` event once when there are duplicated broker close() calls

Added duplicated broker close test

---

README.md
lib/client.js
lib/handlers/connect.js
lib/handlers/index.js
lib/write.js
test/basic.js
test/connect.js
test/events.js

- `connecting`: show we are in CONNECT phase. Please noted that `connackSent` does not mean reset `connecting` to false and set `connected` to true. We still need to procceed the last step, pushing (QoS>0 and !clean) / retain messages to clients
- `connected` should be flagged true when `clientReady`/`connected` is emitted
- `closed`: show client closed state

Introduce connecting and closed metadata

---

lib/handlers/connect.js
test/auth.js

- User could define their own auth error message raised in `clientError`
- no custom error message / empty error message will be applied to the internal one
- User could define the CONNACK return code between 2 and 5. If out of ranges, 5 instead.

Allow user defined their error auth message

---

aedes.d.ts
test/client-pub-sub.js
test/types/index.ts

Added test on broker.subscribe & broker.unsubscribe function

---

aedes.js
package.json
test/auth.js
test/basic.js
test/client-pub-sub.js
test/qos1.js
test/qos2.js

- use `readable-stream` rather than `stream`
- fix tests after updating aedes-packet to v2.3.0

Fixed tests & use readable-stream

---

aedes.d.ts
aedes.js
docs/Aedes.md
lib/handlers/connect.js
test/connect.js

feat: Max clients Id length option for MQTT 3.1.0

---

docs/Client.md
lib/client.js
lib/handlers/unsubscribe.js
test/meta.js

We're better not to inject a custom key `close` into one of argument in `handleUnSubscribe` fn. Malicious unsubscribe packet may break aedes unsubscribe logic.

Handle unsubscription safer while client closes

---

test/meta.js

In https://github.com/moscajs/aedes/pull/408, we remove the `restore` extra key in subscription packet structure, not to break aedes logic.

Added test on unrecognised params in sub packet structure

---

lib/write.js
package.json
test/basic.js

@mcollina this should fix unhandled expections when a non-valid packet is write to stream

fix: catch writeToStream errors

---

lib/client.js
lib/handlers/connect.js
lib/handlers/publish.js
lib/qos-packet.js
lib/write.js
test/basic.js
test/qos1.js
test/qos2.js

Actually [write](https://github.com/moscajs/aedes/blob/master/lib/write.js#L5) doesn't return errors to done callback but insteed it calls `client._onError` that will emit a clientError/connectionError event and disconnect the client. This could cause some memory leaks as when an error occurs the write callback is never called

fix: write leaks

---

lib/handlers/publish.js
test/qos2.js

When a qos2 publish is received, `client.broker.persistence.incomingStorePacket` was called after writing the packet to the stream, this was causing some race conditions that could cause the error explained in #509 issue
Fixes #509

fix: no such packet error with QoS 2

---

lib/client.js
test/client-pub-sub.js

deliverQos/deliver0 functions are bounded in subscribe and used then by mqemitters to deliver messages to clients, the callbacks of those functions should NEVER return an error in callback as it is not catched by mqemitter and could cause unhandled exceptions

fix: don't pass writeQos errors in packet cb

---

aedes.d.ts
aedes.js
docs/Aedes.md
examples/proxy/index.js
lib/handlers/connect.js
test/connect.js
test/types/index.ts

With this feature users will be able to access and modify a connect packet in `aedes.preConnect` handler
This will be a __BREAKING CHANGE__ for users that are using `preConnect`

feat: add `packet` to `aedes.preConnect`

---

docs/Client.md
lib/handlers/connect.js
package.json

fix: replace shortid with hyperid #565

---

lib/handlers/connect.js
test/qos1.js

This is the same issue as reported here:
https://github.com/rvagg/through2/issues/32#issuecomment-62645342
This orignial filled the streams internal buffer because there is no destination stream.
The "client" object returned as the second argument in `writeCallback` was trying to be forwarded

fix: `emptyQueue` hitting its high water mark

---

README.md
aedes.js
docs/Aedes.md
lib/handlers/subscribe.js
package.json
test/client-pub-sub.js
test/retain.js

The incoming mosquitto bridge connections add 128 to the protocol
version to indicate ras=true and nl=true.
Support for this was added in mqtt-packet with
https://github.com/mqttjs/mqtt-packet/pull/106
Subscriptions from these connections will have ras=true and nl=true
When publishing to these connections, aedes will now
copy the Packet and set retain to false only if ras is not true.
Fixes #329

feat(bridge): support incoming mosquitto bridge connections

---

aedes.d.ts

missing the "export * from './types/packet"  in order to have packet types available (typescript)

chore(types): include types/packet in aedes.d.ts

---

types/client.d.ts
types/instance.d.ts

Aedes and Client interfaces has been upgraded as an extends from EventEmitter in order to allow a complete events management in TypeScript applications

fix: upgrade Aedes.d.ts and Client to extends from EventEmitter

---

aedes.js
docs/Aedes.md
lib/handlers/subscribe.js
lib/handlers/unsubscribe.js
lib/utils.js
test/basic.js

Fixes #597
Is this a breaking change in your opinion? @mcollina

fix: publish to `$SYS/` not allowed to prevent DoS

---

types/instance.d.ts

This fixes runtime TypeError when using `AuthErrorCode.NOT_AUTHORIZED` in TypeScript.

fix(types): use const enum for AuthErrorCode to avoid runtime error

---

test/qos1.js

In PR #583, the fix is valid but the unit test does not. The test is still pass when we revert the line back to
``` js
packet.writeCallback = next
``` 
The PR mentioned Aedes uses through2 and suffers similar bugs. The claim is partially correct. We need to do a fix but it is due to the nodejs Transform callback behaviour, in our case it is `writeCallback` call. We could refer to nodejs doc https://nodejs.org/docs/latest-v16.x/api/stream.html#transform_transformchunk-encoding-callback
> The callback function must be called only when the current chunk is completely consumed. The first argument passed to the callback must be an Error object if an error occurred while processing the input or null otherwise. If a second argument is passed to the callback, it will be forwarded on to the …

fix: enhance test on pr 583

---

lib/handlers/subscribe.js
test/auth.js
test/retain.js

Fixes #719 
QoS 128 means the subscribe has failed so we shouldn't send any retained message in that case. Also the qos set in `subs` array passed as second argument in `subscribe` event should match the granted qos of each topic and not the qos sent in the subscribe request

fix: don't send retained messages when granted QoS is 128 and set granted QoS in `subscribe` event subs

---

aedes.js
lib/utils.js
package.json

This aims to reduce one dependency.
Hope I implement well for `writev` function

chore: drop bulk-write-stream

---

types/packet.d.ts

As discussed in https://github.com/moscajs/aedes-cached-persistence/pull/52#issuecomment-1124580516
Next step will be to import this definition in `aedes-persistence`
Kind regards,
Hans

fix(types): ClientId type definition

---

types/packet.d.ts

As discussed in https://github.com/moscajs/aedes/pull/741#issuecomment-1126075779
Kind regards,
Hans

fix(types): remove superfluous ClientId type definition

---

aedes.d.ts
package.json
test/types/aedes.test-d.ts
types/.eslintrc.json
types/client.d.ts
types/instance.d.ts
types/packet.d.ts
types/tsconfig.json

A breaking change in TS
- drop Server() and Aedes() ts export functions
- add a prefix in aedes modules 
Sample usage
``` js
import Server, { Aedes } from 'aedes:server'
// the above is same as below
// import Server, { Aedes } from 'aedes'
let broker = new Server()
broker = new Aedes()
```

feat: add a prefix in aedes module and drop ts functions

---

aedes.js
docs/Aedes.md
test/types/aedes.test-d.ts
test/will.js
types/instance.d.ts

This is a response to #767, to authorise old wills be published. The `client` will be `null` in `authorizePublish` in this case.

fix: authorize old wills

---

test/types/aedes.test-d.ts
types/instance.d.ts

Add missing type parameter of `request: IncomingMessage` on `aedes.handle` method.
[aedes.js#L55](https://github.com/moscajs/aedes/blob/main/aedes.js#L55)
```ts
...
matchEmptyLevels: true // [MQTT-4.7.1-3]
})
this.handle = function handle (conn, req) {
conn.setMaxListeners(opts.concurrency * 2)
// create a new Client instance for a new connection
// return, just to please standard
...
```

fix(types): `aedes.handle` type definition

---

test/types/aedes.test-d.ts
types/instance.d.ts

The username and password variables have the undefined type when not set in the MQTTX client.

fix(types): update username and password type definition

---

lib/client.js
test/will.js

I was using aedes-persistence-redis and noticed that if clients connect with a will message then the keys weren't being deleted on a clean disconnect
The keys should always be removed from the persistence regardless if the the client disconnects cleanly or not.  When the client disconnects, the will no longer should matter so we can delete it. If the client connects again with another will, then we can retain that one.

fix: delete will from persistence on disconnect

---

aedes.js
lib/handlers/subscribe.js
test/events.js

This pr is related to the https://github.com/moscajs/aedes/issues/928 
The made fix **didn't decrease connectedClients** counter, which lead to incorrect amount of clients provided by broker.
One more issue is related to constant increase of subscriptions. My broker has a lot of unique clients per day with short keepAliveTimeout and frequent reconnection and subscription rate. I suspect that the problem is in the **authorizeSubscribe** method which can be async. This may lead to subscription for closed clients. In this case broker will never unsub them. 
Unfortunately, I am limited in experiments on production to prove my idea, but the proposed fix seems reasonable and harmless to me.

fix: memory leak in connected clients counter

---

package.json

Followed the guideline in the [ESM](https://nodejs.org/api/esm.html#esm_package_json_type_field), we explicitly state module type.

chore: add type commonjs

---

package.json
test/client-pub-sub.js

This PR updates aedes-persistence to version 10.2.0
It does *not* yet use the async persistence interface!
However Aedes should work ok with the callback interface of 10.2.0
Installing version 10.2.0 highlighted a race condition in test/client-pub-sub.js where the client would subscribe to the announcement of its own connect. This is no problem with synchronous persistence, but since we now run async the client  misses its own connect announcement.
Kind regards,
Hans

chore:  update aedes-persistence to 10.2.0

---

aedes.js
lib/client.js
lib/handlers/connect.js
lib/handlers/publish.js
lib/handlers/pubrec.js
lib/handlers/pubrel.js
lib/handlers/subscribe.js
lib/handlers/unsubscribe.js
lib/qos-packet.js
test/basic.js

This PR migrates Aedes to ES6 class syntax.
This should help in further refactoring.
I tried to migrate everything that looked like a class but I might have missed one as `this` is also used in functions that are not constructors but whose this will be set by `parallel` etc.
Kind regards,
Hans

chore: migrate to ES6 classes

---

.github/actions/sticky-pr-comment/action.yml
.github/workflows/benchmark-compare-serial.yml
benchmarks/report.js
benchmarks/runBenchmarks.js

This PR adds Github actions to automate benchmark running on PR requests
It will create a [Github Job Summary](https://github.blog/news-insights/product-news/supercharging-github-actions-with-job-summaries/) of the benchmark and add it to the benchmark action (see https://github.com/moscajs/aedes/actions/runs/16239498783#summary-45853979456 )
The benchmark steps run serialized in the hope that performance on a single runner does not vary too much.
I have been building testing this using https://github.com/seriousme/aedes/pull/1 which also shows how it operates.
It also shows that variation between results is inevitable, even when running on the same runner and the Aedes code is identical !!
In https://github.com/seriousme/aedes/pull/1  I was able to add the comment automatically to the PR …

feat: automate benchmark on PR requests using Github Actions
