moscajs/aedes

- .travis.yml
- aedes.js
- lib/client.js
- lib/write.js
- package.json
- test/qos2.js
This gives us a 5x perf improvement!
> Write the packet directly to the stream

- lib/handlers/unsubscribe.js
- test/basic.js
Unsubscribe request for a topic that hasn't been subscribed is not handeld.
> fixed unsubscribe handler exception

- .travis.yml
- README.md
- lib/handlers/puback.js
- package.json
- test/client-pub-sub.js
See:
https://github.com/mcollina/aedes/pull/39/files/7897baca0c9db516cd179f3d64497c9527b84f5a#r58312647
> Renamed the 'deliver' event to 'ack'

- lib/client.js
- lib/handlers/pubrec.js
- test/qos2.js
Fixes #83.
@GavinDmello @battuashwik please confirm
> Do not try to update stored packet on PUBREC with clean=true.

- lib/client.js
- test/auth.js
- test/not-blocking.js
cc @gavindmello @yutter @wuhkuh 
This is a failing test.
> added a test with overlapping subscription

- lib/client.js
- test/will.js
Fixes #109.
@jmholzinger can you verify it if fixes your bug?
> Do not emit the will twice if close() is called twice.

- README.md
- lib/client.js
- test/client-pub-sub.js
I just used the PR related to `https://github.com/mcollina/aedes/issues/114`
Let me know if a test case is needed
> added unsubscribe function in client

- lib/client.js
- lib/handlers/connect.js
- test/auth.js
Hi @mcollina: what do you think of this test? I can try to fix it if it's legit and you have any hints on where I should look. Thanks.
> authorizePublish gets called before authenticate finishes

- lib/client.js
- test/will.js
Fixes https://github.com/mcollina/aedes/issues/180
> fixed Will message not removed from persistence after publish

- lib/client.js
> Removed a bad hack for older Node.js

- README.md
- package.json
Give a big thanks for author, our collaborators and a great community
> Added collaborators

- test/auth.js
Passing CI test requires https://github.com/mcollina/aedes-packet/pull/5
> Enhance auth QoS 0 tests

- aedes.js
- test/meta.js
This fix is similar to PR https://github.com/mcollina/aedes/pull/287
> Packet in broker.published() should be identical to the original one

- lib/client.js
- lib/handlers/index.js
- test/will.js
1. Added a unit test - not deliver will when client DISCONNECT
2. clean up last will variable even client closes
>  Added a last will unit test when DISCONNECTS & clean up will in client.close()

- lib/handlers/subscribe.js
- test/events.js
> The Server MUST NOT match Topic Filters starting with a wildcard character (# or +) with Topic Names beginning with a $ character [MQTT-4.7.2-1]
> Block $ prefix topic in subscriptions

- .gitignore
- examples/clusters/index.js
- examples/clusters/package.json
@mcollina Here you are. Let me know if I have to change something
> Clusters example #146

- README.md
- package.json
This commit also update the CI badges by github actions.
> [chore] Changed to a new repo after migrating to a org

- package.json
> Bump mqemitter@4.0.0

- lib/client.js
- lib/handlers/connect.js
- test/basic.js
- test/client-pub-sub.js
- test/connect.js
- test/topics.js
- test/will.js
> Extend coverage to 100%

- package.json
- test/connect.js
- test/not-blocking.js
- test/will.js
Use fake timers to raise the reliability.
> Enhanced not-blocking tests by fake timers

- README.md
- docs/Examples.md
> Clusters docs

- aedes.d.ts
- docs/Client.md
- lib/client.js
- lib/handlers/connect.js
- test/connect.js
- test/types/index.ts
as title, we expose `CONNECT` protocol version into Client that add flexibility to our users to fine-tune their hook handlers.
> Expose protocol version in Client object

- README.md
- state the package is currently maintained
- and welcome anyone to submit PRs
> Add more badges in README.md

- test/basic.js
Add test on a single/multiple subscriptions in QoS 0 [clean=false/true], and QoS 1 [clean=false/true]
> Enhance subscription basic tests

- docs/Aedes.md
- lib/handlers/subscribe.js
- test/client-pub-sub.js
> Return granted qos in broker subscribe event and better subAck docs

- lib/handlers/unsubscribe.js
- test/client-pub-sub.js
> fix: remove subs only when clean flag is false

- docs/Aedes.md
> docs: authorizePublish clarification

- README.md
Hi!
We recently change mosca for aedes for our MQTT support in Kuzzle and we are very happy of it!
> Add Kuzzle to "Made with aedes" section

- lib/client.js
> fix: clean up the write callbacks in case of error

- lib/handlers/connect.js
- test/connect.js
Could be a possible fix of #483
> fix: prevent client connection to be closed when doing connack

- types/instance.d.ts
Add handler types to Aedes object
> fix(types): add handlers types to aedes options

- .github/workflows/ci.yml
- package.json
As requested in https://github.com/moscajs/aedes/pull/732
> chore: update CI to remove Node 12

- lib/utils.js
- test/topics.js
> fix: validation of `null` topics

- aedes.js
- docs/Aedes.md
- lib/handlers/connect.js
- test/connect.js
- test/types/aedes.test-d.ts
- types/instance.d.ts
Hi,
this is a PR for this discussion: https://github.com/moscajs/aedes/discussions/865
> feat: add `opts.keepaliveLimit`

- lib/handlers/connect.js
> fix: remove console.error (#951)
